/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import demo.AddListingTest;
import demo.ApproveListing;
import demo.DeleteProperty;
import demo.DeleteUser;
import demo.EditUser;
import demo.Methods;
import demo.MigrateToCorporate;
import demo.PostRequesttest;
import demo.SearchTest;
import demo.SignupTest;
import demo.logintest;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.*;
import org.junit.internal.TextListener;
import org.junit.runner.JUnitCore;

/**
 *
 * @author Omar Fekry
 */
public class AdminFrame extends javax.swing.JFrame {
    
    /**
     * Creates new form MainFrame
     */
    public AdminFrame() {
        initComponents();   
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        layeredPane = new javax.swing.JLayeredPane();
        mainPanel = new javax.swing.JPanel();
        EditUserCheckBox = new javax.swing.JCheckBox();
        ConvertToCoorperateCheckBox = new javax.swing.JCheckBox();
        EditPropertyCheckBox = new javax.swing.JCheckBox();
        loginEditButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        alLLEditButton = new javax.swing.JButton();
        ApprovePropertyCheckBox = new javax.swing.JCheckBox();
        signupEditButton = new javax.swing.JButton();
        DeleteUserCheckBox = new javax.swing.JCheckBox();
        prTTEditButton = new javax.swing.JButton();
        buttonPanel = new javax.swing.JPanel();
        selectAllButton = new javax.swing.JButton();
        deselectAllButton = new javax.swing.JButton();
        testButton = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        searchEditButton = new javax.swing.JButton();
        chromeButton = new javax.swing.JButton();
        edgeButton = new javax.swing.JButton();
        firefoxButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        DeletePropertyCheckBox = new javax.swing.JCheckBox();
        alLLEditButton1 = new javax.swing.JButton();
        DeleteOfferCheckBox = new javax.swing.JCheckBox();
        alLLEditButton2 = new javax.swing.JButton();
        DeleteRequestCheckBox = new javax.swing.JCheckBox();
        alLLEditButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rentup Automated Tester");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(915, 735));
        setMinimumSize(new java.awt.Dimension(915, 735));
        setName("mainFrame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(915, 735));
        setResizable(false);
        setSize(new java.awt.Dimension(915, 735));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        layeredPane.setBackground(new java.awt.Color(255, 255, 255));
        layeredPane.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 0, 255)));
        layeredPane.setMaximumSize(new java.awt.Dimension(900, 700));
        layeredPane.setMinimumSize(new java.awt.Dimension(900, 700));
        layeredPane.setLayout(new java.awt.GridBagLayout());

        mainPanel.setBackground(new java.awt.Color(249, 249, 249));
        mainPanel.setToolTipText("");
        mainPanel.setMaximumSize(new java.awt.Dimension(900, 700));
        mainPanel.setMinimumSize(new java.awt.Dimension(900, 700));
        mainPanel.setName("mainPanel"); // NOI18N
        mainPanel.setPreferredSize(new java.awt.Dimension(900, 700));
        mainPanel.setLayout(new java.awt.GridBagLayout());

        EditUserCheckBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        EditUserCheckBox.setSelected(true);
        EditUserCheckBox.setText("EditUser");
        EditUserCheckBox.setName("EditUserCheckBox"); // NOI18N
        EditUserCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditUserCheckBoxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 45;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(6, 25, 6, 0);
        mainPanel.add(EditUserCheckBox, gridBagConstraints);

        ConvertToCoorperateCheckBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ConvertToCoorperateCheckBox.setSelected(true);
        ConvertToCoorperateCheckBox.setText("ConvertToCoorperate");
        ConvertToCoorperateCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConvertToCoorperateCheckBoxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.ipadx = 45;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(6, 25, 6, 0);
        mainPanel.add(ConvertToCoorperateCheckBox, gridBagConstraints);

        EditPropertyCheckBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        EditPropertyCheckBox.setSelected(true);
        EditPropertyCheckBox.setText("EditProperty");
        EditPropertyCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditPropertyCheckBoxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 45;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(6, 25, 6, 0);
        mainPanel.add(EditPropertyCheckBox, gridBagConstraints);

        loginEditButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        loginEditButton.setText("Edit Values");
        loginEditButton.setName("loginEditButton"); // NOI18N
        loginEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginEditButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 16, 0, 16);
        mainPanel.add(loginEditButton, gridBagConstraints);

        ConvertToCoorperate.setMaximumSize(new java.awt.Dimension(35, 35));
        ConvertToCoorperate.setMinimumSize(new java.awt.Dimension(35, 35));
        ConvertToCoorperate.setPreferredSize(new java.awt.Dimension(35, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 11, 0, 0);
        mainPanel.add(ConvertToCoorperate, gridBagConstraints);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setText("General:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(16, 15, 16, 0);
        mainPanel.add(jLabel10, gridBagConstraints);

        alLLEditButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        alLLEditButton.setText("Edit Values");
        alLLEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alLLEditButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 16, 0, 16);
        mainPanel.add(alLLEditButton, gridBagConstraints);

        ApprovePropertyCheckBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ApprovePropertyCheckBox.setSelected(true);
        ApprovePropertyCheckBox.setText("ApproveProperty");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 45;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(6, 25, 6, 0);
        mainPanel.add(ApprovePropertyCheckBox, gridBagConstraints);

        signupEditButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        signupEditButton.setText("Edit Values");
        signupEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupEditButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 16, 0, 16);
        mainPanel.add(signupEditButton, gridBagConstraints);

        DeleteUserCheckBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        DeleteUserCheckBox.setSelected(true);
        DeleteUserCheckBox.setText("DeleteUser");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 45;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(6, 25, 6, 0);
        mainPanel.add(DeleteUserCheckBox, gridBagConstraints);

        DeleteUser.setMaximumSize(new java.awt.Dimension(35, 35));
        DeleteUser.setMinimumSize(new java.awt.Dimension(35, 35));
        DeleteUser.setPreferredSize(new java.awt.Dimension(35, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 11, 0, 0);
        mainPanel.add(DeleteUser, gridBagConstraints);

        EditProperty.setMaximumSize(new java.awt.Dimension(35, 35));
        EditProperty.setMinimumSize(new java.awt.Dimension(35, 35));
        EditProperty.setName(""); // NOI18N
        EditProperty.setPreferredSize(new java.awt.Dimension(35, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 11, 0, 0);
        mainPanel.add(EditProperty, gridBagConstraints);

        prTTEditButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        prTTEditButton.setText("Edit Values");
        prTTEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prTTEditButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 16, 0, 16);
        mainPanel.add(prTTEditButton, gridBagConstraints);

        buttonPanel.setBackground(mainPanel.getBackground());
        buttonPanel.setMaximumSize(new java.awt.Dimension(362, 35));
        buttonPanel.setMinimumSize(new java.awt.Dimension(362, 35));
        buttonPanel.setName("buttonPanel"); // NOI18N
        buttonPanel.setPreferredSize(new java.awt.Dimension(362, 35));
        buttonPanel.setLayout(new java.awt.GridBagLayout());

        selectAllButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        selectAllButton.setText("Select All");
        selectAllButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        selectAllButton.setName("loginEditButton"); // NOI18N
        selectAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectAllButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        buttonPanel.add(selectAllButton, gridBagConstraints);

        deselectAllButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        deselectAllButton.setText("Deselect All");
        deselectAllButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        deselectAllButton.setName("loginEditButton"); // NOI18N
        deselectAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deselectAllButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 4);
        buttonPanel.add(deselectAllButton, gridBagConstraints);

        testButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        testButton.setText("Start Testing");
        testButton.setMaximumSize(new java.awt.Dimension(140, 31));
        testButton.setMinimumSize(new java.awt.Dimension(140, 31));
        testButton.setName("loginEditButton"); // NOI18N
        testButton.setPreferredSize(new java.awt.Dimension(140, 31));
        testButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 0.1;
        buttonPanel.add(testButton, gridBagConstraints);

        jComboBox2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Production", "Development", "Staging" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 3);
        buttonPanel.add(jComboBox2, gridBagConstraints);

        jComboBox3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Desktop", "Mobile" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 22, 0, 4);
        buttonPanel.add(jComboBox3, gridBagConstraints);

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("MainFrame");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        buttonPanel.add(jButton1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(17, 13, 0, 13);
        mainPanel.add(buttonPanel, gridBagConstraints);

        ApproveProperty.setMaximumSize(new java.awt.Dimension(35, 35));
        ApproveProperty.setMinimumSize(new java.awt.Dimension(35, 35));
        ApproveProperty.setPreferredSize(new java.awt.Dimension(35, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 11, 0, 0);
        mainPanel.add(ApproveProperty, gridBagConstraints);

        searchEditButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        searchEditButton.setText("Edit Values");
        searchEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchEditButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 16, 0, 16);
        mainPanel.add(searchEditButton, gridBagConstraints);

        EditUserLabel2.setMaximumSize(new java.awt.Dimension(35, 35));
        EditUserLabel2.setMinimumSize(new java.awt.Dimension(35, 35));
        EditUserLabel2.setName("loginStatusLabel"); // NOI18N
        EditUserLabel2.setPreferredSize(new java.awt.Dimension(35, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 9);
        mainPanel.add(EditUserLabel2, gridBagConstraints);

        DeleteUser2.setMaximumSize(new java.awt.Dimension(35, 35));
        DeleteUser2.setMinimumSize(new java.awt.Dimension(35, 35));
        DeleteUser2.setPreferredSize(new java.awt.Dimension(35, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 9);
        mainPanel.add(DeleteUser2, gridBagConstraints);

        ApproveProperty2.setMaximumSize(new java.awt.Dimension(35, 35));
        ApproveProperty2.setMinimumSize(new java.awt.Dimension(35, 35));
        ApproveProperty2.setPreferredSize(new java.awt.Dimension(35, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 9);
        mainPanel.add(ApproveProperty2, gridBagConstraints);

        EditProperty2.setMaximumSize(new java.awt.Dimension(35, 35));
        EditProperty2.setMinimumSize(new java.awt.Dimension(35, 35));
        EditProperty2.setName(""); // NOI18N
        EditProperty2.setPreferredSize(new java.awt.Dimension(35, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 9);
        mainPanel.add(EditProperty2, gridBagConstraints);

        ConvertToCoorperate2.setMaximumSize(new java.awt.Dimension(35, 35));
        ConvertToCoorperate2.setMinimumSize(new java.awt.Dimension(35, 35));
        ConvertToCoorperate2.setPreferredSize(new java.awt.Dimension(35, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 9);
        mainPanel.add(ConvertToCoorperate2, gridBagConstraints);

        EditUserLabel1.setMaximumSize(new java.awt.Dimension(35, 35));
        EditUserLabel1.setMinimumSize(new java.awt.Dimension(35, 35));
        EditUserLabel1.setName("loginStatusLabel"); // NOI18N
        EditUserLabel1.setPreferredSize(new java.awt.Dimension(35, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.weighty = 0.1;
        mainPanel.add(EditUserLabel1, gridBagConstraints);

        DeleteUser1.setMaximumSize(new java.awt.Dimension(35, 35));
        DeleteUser1.setMinimumSize(new java.awt.Dimension(35, 35));
        DeleteUser1.setPreferredSize(new java.awt.Dimension(35, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.weighty = 0.1;
        mainPanel.add(DeleteUser1, gridBagConstraints);

        ApproveProperty1.setMaximumSize(new java.awt.Dimension(35, 35));
        ApproveProperty1.setMinimumSize(new java.awt.Dimension(35, 35));
        ApproveProperty1.setPreferredSize(new java.awt.Dimension(35, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.weighty = 0.1;
        mainPanel.add(ApproveProperty1, gridBagConstraints);

        EditProperty1.setMaximumSize(new java.awt.Dimension(35, 35));
        EditProperty1.setMinimumSize(new java.awt.Dimension(35, 35));
        EditProperty1.setName(""); // NOI18N
        EditProperty1.setPreferredSize(new java.awt.Dimension(35, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.weighty = 0.1;
        mainPanel.add(EditProperty1, gridBagConstraints);

        ConvertToCoorperate1.setMaximumSize(new java.awt.Dimension(35, 35));
        ConvertToCoorperate1.setMinimumSize(new java.awt.Dimension(35, 35));
        ConvertToCoorperate1.setPreferredSize(new java.awt.Dimension(35, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.weighty = 0.1;
        mainPanel.add(ConvertToCoorperate1, gridBagConstraints);

        EditUserLabel.setMaximumSize(new java.awt.Dimension(35, 35));
        EditUserLabel.setMinimumSize(new java.awt.Dimension(35, 35));
        EditUserLabel.setName("loginStatusLabel"); // NOI18N
        EditUserLabel.setPreferredSize(new java.awt.Dimension(35, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 11, 0, 0);
        mainPanel.add(EditUserLabel, gridBagConstraints);

        chromeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/chrome.png"))); // NOI18N
        chromeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chromeButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weighty = 0.1;
        mainPanel.add(chromeButton, gridBagConstraints);

        edgeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/edge_gray.png"))); // NOI18N
        edgeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edgeButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weighty = 0.1;
        mainPanel.add(edgeButton, gridBagConstraints);

        firefoxButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/firefox_gray.png"))); // NOI18N
        firefoxButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firefoxButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weighty = 0.1;
        mainPanel.add(firefoxButton, gridBagConstraints);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 0.1;
        mainPanel.add(jSeparator1, gridBagConstraints);

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 0.1;
        mainPanel.add(jSeparator2, gridBagConstraints);

        DeletePropertyCheckBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        DeletePropertyCheckBox.setSelected(true);
        DeletePropertyCheckBox.setText("DeleteProperty");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 45;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(6, 25, 6, 0);
        mainPanel.add(DeletePropertyCheckBox, gridBagConstraints);

        alLLEditButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        alLLEditButton1.setText("Edit Values");
        alLLEditButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alLLEditButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 16, 0, 16);
        mainPanel.add(alLLEditButton1, gridBagConstraints);

        DeleteProperty.setMaximumSize(new java.awt.Dimension(35, 35));
        DeleteProperty.setMinimumSize(new java.awt.Dimension(35, 35));
        DeleteProperty.setPreferredSize(new java.awt.Dimension(35, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 11, 0, 0);
        mainPanel.add(DeleteProperty, gridBagConstraints);

        DeleteProperty1.setMaximumSize(new java.awt.Dimension(35, 35));
        DeleteProperty1.setMinimumSize(new java.awt.Dimension(35, 35));
        DeleteProperty1.setPreferredSize(new java.awt.Dimension(35, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.weighty = 0.1;
        mainPanel.add(DeleteProperty1, gridBagConstraints);

        DeleteProperty2.setMaximumSize(new java.awt.Dimension(35, 35));
        DeleteProperty2.setMinimumSize(new java.awt.Dimension(35, 35));
        DeleteProperty2.setPreferredSize(new java.awt.Dimension(35, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 9);
        mainPanel.add(DeleteProperty2, gridBagConstraints);

        DeleteOfferCheckBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        DeleteOfferCheckBox.setSelected(true);
        DeleteOfferCheckBox.setText("DeleteOffer");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 45;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(6, 25, 6, 0);
        mainPanel.add(DeleteOfferCheckBox, gridBagConstraints);

        alLLEditButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        alLLEditButton2.setText("Edit Values");
        alLLEditButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alLLEditButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 16, 0, 16);
        mainPanel.add(alLLEditButton2, gridBagConstraints);

        DeleteOffer.setMaximumSize(new java.awt.Dimension(35, 35));
        DeleteOffer.setMinimumSize(new java.awt.Dimension(35, 35));
        DeleteOffer.setPreferredSize(new java.awt.Dimension(35, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 11, 0, 0);
        mainPanel.add(DeleteOffer, gridBagConstraints);

        DeleteOffer1.setMaximumSize(new java.awt.Dimension(35, 35));
        DeleteOffer1.setMinimumSize(new java.awt.Dimension(35, 35));
        DeleteOffer1.setPreferredSize(new java.awt.Dimension(35, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.weighty = 0.1;
        mainPanel.add(DeleteOffer1, gridBagConstraints);

        DeleteOffer2.setMaximumSize(new java.awt.Dimension(35, 35));
        DeleteOffer2.setMinimumSize(new java.awt.Dimension(35, 35));
        DeleteOffer2.setPreferredSize(new java.awt.Dimension(35, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 9);
        mainPanel.add(DeleteOffer2, gridBagConstraints);

        DeleteRequestCheckBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        DeleteRequestCheckBox.setSelected(true);
        DeleteRequestCheckBox.setText("DeleteRequest");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 45;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(6, 25, 6, 0);
        mainPanel.add(DeleteRequestCheckBox, gridBagConstraints);

        alLLEditButton3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        alLLEditButton3.setText("Edit Values");
        alLLEditButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alLLEditButton3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 16, 0, 16);
        mainPanel.add(alLLEditButton3, gridBagConstraints);

        DeleteRequest.setMaximumSize(new java.awt.Dimension(35, 35));
        DeleteRequest.setMinimumSize(new java.awt.Dimension(35, 35));
        DeleteRequest.setPreferredSize(new java.awt.Dimension(35, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 11, 0, 0);
        mainPanel.add(DeleteRequest, gridBagConstraints);

        DeleteRequest1.setMaximumSize(new java.awt.Dimension(35, 35));
        DeleteRequest1.setMinimumSize(new java.awt.Dimension(35, 35));
        DeleteRequest1.setPreferredSize(new java.awt.Dimension(35, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.weighty = 0.1;
        mainPanel.add(DeleteRequest1, gridBagConstraints);

        DeleteRequest2.setMaximumSize(new java.awt.Dimension(35, 35));
        DeleteRequest2.setMinimumSize(new java.awt.Dimension(35, 35));
        DeleteRequest2.setPreferredSize(new java.awt.Dimension(35, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 9);
        mainPanel.add(DeleteRequest2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        layeredPane.add(mainPanel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(layeredPane, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alLLEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alLLEditButtonActionPerformed
        MigrateToCorporatePanel panel = new MigrateToCorporatePanel(layeredPane);
        
        layeredPane.add(panel, new java.awt.GridBagConstraints());
        panel.setSize(layeredPane.getWidth(), layeredPane.getHeight());
        layeredPane.setLayer(panel, 1);
        mainPanel.setVisible(false);
        layeredPane.revalidate();
        layeredPane.repaint();
    }//GEN-LAST:event_alLLEditButtonActionPerformed

    private void prTTEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prTTEditButtonActionPerformed
        // TODO add your handling code here:
        PostRequestPanel panel = new PostRequestPanel(layeredPane);
        
        layeredPane.add(panel, new java.awt.GridBagConstraints());
        panel.setSize(layeredPane.getWidth(), layeredPane.getHeight());
        layeredPane.setLayer(panel, 1);
        mainPanel.setVisible(false);
        layeredPane.revalidate();
        layeredPane.repaint();
    }//GEN-LAST:event_prTTEditButtonActionPerformed

    private void signupEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupEditButtonActionPerformed
        DeleteUserPanel panel = new DeleteUserPanel(layeredPane);
        
        layeredPane.add(panel, new java.awt.GridBagConstraints());
        panel.setSize(layeredPane.getWidth(), layeredPane.getHeight());
        layeredPane.setLayer(panel, 1);
        mainPanel.setVisible(false);
        layeredPane.revalidate();
        layeredPane.repaint();
    }//GEN-LAST:event_signupEditButtonActionPerformed
                                  
    private void loginEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginEditButtonActionPerformed
        EditUserPanel panel = new EditUserPanel(layeredPane);
        
        layeredPane.add(panel, new java.awt.GridBagConstraints());
        panel.setSize(layeredPane.getWidth(), layeredPane.getHeight());
        layeredPane.setLayer(panel, 1);
        mainPanel.setVisible(false);
        layeredPane.revalidate();
        layeredPane.repaint();
    }//GEN-LAST:event_loginEditButtonActionPerformed

    private void EditUserCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditUserCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditUserCheckBoxActionPerformed

    private void searchEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchEditButtonActionPerformed
        
        ApproveListingPanel panel = new ApproveListingPanel(layeredPane);
        
        layeredPane.add(panel, new java.awt.GridBagConstraints());
        panel.setSize(layeredPane.getWidth(), layeredPane.getHeight());
        layeredPane.setLayer(panel, 1);
        mainPanel.setVisible(false);
        layeredPane.revalidate();
        layeredPane.repaint();
        
        
        
        
    }//GEN-LAST:event_searchEditButtonActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        checks.add(EditUserCheckBox);
        checks.add(DeleteUserCheckBox);
        checks.add(ApprovePropertyCheckBox);
        checks.add(EditPropertyCheckBox);
        checks.add(DeletePropertyCheckBox);
        checks.add(DeleteOfferCheckBox);
        checks.add(DeleteRequestCheckBox);
        checks.add(ConvertToCoorperateCheckBox);
        
        labels[0][0] = EditUserLabel;
        labels[1][0] = DeleteUser;
        labels[2][0] = ApproveProperty;
        labels[3][0] = EditProperty;
        labels[4][0] = DeleteProperty;
        labels[5][0] = DeleteOffer;
        labels[6][0] = DeleteRequest;
        labels[7][0] = ConvertToCoorperate;
     
        
        labels[0][1] = EditUserLabel1;
        labels[1][1] = DeleteUser1;
        labels[2][1] = ApproveProperty1;
        labels[3][1] = EditProperty1;
        labels[4][1] = DeleteProperty1;
        labels[5][1] = DeleteOffer1;
        labels[6][1] = DeleteRequest1;
        labels[7][1] = ConvertToCoorperate1;
     
        
        labels[0][2] = EditUserLabel2;
        labels[1][2] = DeleteUser2;
        labels[2][2] = ApproveProperty2;
        labels[3][2] = EditProperty2;
        labels[4][2] = DeleteProperty2;
        labels[5][2] = DeleteOffer2;
        labels[6][2] = DeleteRequest2;
        labels[7][2] = ConvertToCoorperate2;
       
        
    }//GEN-LAST:event_formWindowOpened

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void deselectAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deselectAllButtonActionPerformed
        for(JCheckBox cb : checks)
        cb.setSelected(false);
    }//GEN-LAST:event_deselectAllButtonActionPerformed

    private void selectAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectAllButtonActionPerformed
        for(JCheckBox cb : checks)
        cb.setSelected(true);
    }//GEN-LAST:event_selectAllButtonActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
        String choice = jComboBox3.getSelectedItem().toString();
        Methods.platform=choice;
        
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void testButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testButtonActionPerformed
        
        if (!chrome && !edge && !firefox){
            JOptionPane.showMessageDialog(this, "Please pick a browser");
            return;
        }
        
        for(int i = 0; i < 8; i++)
            for(JLabel label : labels[i]){
                label.setIcon(null);
                label.repaint();
                label.revalidate();
            }
        
        String domain = jComboBox2.getSelectedItem().toString();
        switch(domain){
            case "Development":
                Methods.domain = "https://dev.rentup.co/";
                break;
            case "Staging":
                Methods.domain = "https://rentup.co/";
                break;
            case "Production":
                Methods.domain = "https://rentup.com.eg/";
                break;
        }
        
        Methods.platform = jComboBox3.getSelectedItem().toString();
        
        ArrayList<String> browsers = new ArrayList<String>();
        if (chrome) browsers.add("Chrome"); else browsers.add("");
        if (edge) browsers.add("Edge"); else browsers.add("");
        if (firefox) browsers.add("Firefox"); else browsers.add("");
        
        for(int i = 0; i < browsers.size(); i++){
        
            if (browsers.get(i).equals("")) continue;
            
            try {
                Thread.sleep(3000);
            } catch (InterruptedException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            Methods.browser = browsers.get(i);
            
            if (EditUserCheckBox.isSelected()){
                labels[0][i].setIcon(new ImageIcon(getClass().getResource("/Resources/loading.gif")));
                final JLabel label = labels[0][i];
                label.repaint();
                label.revalidate();
                JUnitCore junit = new JUnitCore();
                junit.addListener(new TextListener(System.out));
                new Thread(){
                    public void run(){
                        if (junit.run(EditUser.class).wasSuccessful())
                            label.setIcon(new ImageIcon(getClass().getResource("/Resources/check.png")));
                        else
                            label.setIcon(new ImageIcon(getClass().getResource("/Resources/cross.png")));
                    }
                }.start();

            }
            

            if (DeleteUserCheckBox.isSelected()){
                labels[1][i].setIcon(new ImageIcon(getClass().getResource("/Resources/loading.gif")));
                final JLabel label = labels[1][i];
                label.repaint();
                label.revalidate();
                JUnitCore junit = new JUnitCore();
                junit.addListener(new TextListener(System.out));
                new Thread(){
                    public void run(){
                        if (junit.run(DeleteUser.class).wasSuccessful())
                            label.setIcon(new ImageIcon(getClass().getResource("/Resources/check.png")));
                        else
                            label.setIcon(new ImageIcon(getClass().getResource("/Resources/cross.png")));
                    }
                }.start();

            }

            if (ApprovePropertyCheckBox.isSelected()){
                labels[2][i].setIcon(new ImageIcon(getClass().getResource("/Resources/loading.gif")));
                final JLabel label = labels[2][i];
                label.repaint();
                label.revalidate();
                JUnitCore junit = new JUnitCore();
                junit.addListener(new TextListener(System.out));
                new Thread(){
                    public void run(){
                        if (junit.run(ApproveListing.class).wasSuccessful())
                            label.setIcon(new ImageIcon(getClass().getResource("/Resources/check.png")));
                        else
                            label.setIcon(new ImageIcon(getClass().getResource("/Resources/cross.png")));
                    }
                }.start();
            }

            if (EditPropertyCheckBox.isSelected()){
                labels[3][i].setIcon(new ImageIcon(getClass().getResource("/Resources/loading.gif")));
                final JLabel label = labels[3][i];
                label.repaint();
                label.revalidate();
                JUnitCore junit = new JUnitCore();
                junit.addListener(new TextListener(System.out));
                new Thread(){
                    public void run(){
                        if (junit.run(PostRequesttest.class).wasSuccessful())
                            label.setIcon(new ImageIcon(getClass().getResource("/Resources/check.png")));
                        else
                            label.setIcon(new ImageIcon(getClass().getResource("/Resources/cross.png")));
                    }
                }.start();
            }
            
            if (ConvertToCoorperateCheckBox.isSelected()){
                labels[7][i].setIcon(new ImageIcon(getClass().getResource("/Resources/loading.gif")));
                final JLabel label = labels[7][i];
                label.repaint();
                label.revalidate();
                JUnitCore junit = new JUnitCore();
                junit.addListener(new TextListener(System.out));
                new Thread(){
                    public void run(){
                        if (junit.run(MigrateToCorporate.class).wasSuccessful())
                            label.setIcon(new ImageIcon(getClass().getResource("/Resources/check.png")));
                        else
                            label.setIcon(new ImageIcon(getClass().getResource("/Resources/cross.png")));
                    }
                }.start();
            }
            if (DeletePropertyCheckBox.isSelected()){
                labels[4][i].setIcon(new ImageIcon(getClass().getResource("/Resources/loading.gif")));
                final JLabel label = labels[4][i];
                label.repaint();
                label.revalidate();
                JUnitCore junit = new JUnitCore();
                junit.addListener(new TextListener(System.out));
                new Thread(){
                    public void run(){
                        if (junit.run(DeleteProperty.class).wasSuccessful())
                            label.setIcon(new ImageIcon(getClass().getResource("/Resources/check.png")));
                        else
                            label.setIcon(new ImageIcon(getClass().getResource("/Resources/cross.png")));
                    }
                }.start();
            }
        }
    }//GEN-LAST:event_testButtonActionPerformed

    private void chromeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chromeButtonActionPerformed
        if (chrome){
            chromeButton.setIcon(new ImageIcon(getClass().getResource("/Resources/chrome_gray.png")));
            chrome = false;
        }
        else{
            chromeButton.setIcon(new ImageIcon(getClass().getResource("/Resources/chrome.png")));
            chrome = true;
        }
    }//GEN-LAST:event_chromeButtonActionPerformed

    private void edgeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edgeButtonActionPerformed
        if (edge){
            edgeButton.setIcon(new ImageIcon(getClass().getResource("/Resources/edge_gray.png")));
            edge = false;
        }
        else{
            edgeButton.setIcon(new ImageIcon(getClass().getResource("/Resources/edge.png")));
            edge = true;
        }
    }//GEN-LAST:event_edgeButtonActionPerformed

    private void firefoxButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firefoxButtonActionPerformed
        if (firefox){
            firefoxButton.setIcon(new ImageIcon(getClass().getResource("/Resources/firefox_gray.png")));
            firefox = false;
        }
        else{
            firefoxButton.setIcon(new ImageIcon(getClass().getResource("/Resources/firefox.png")));
            firefox = true;
        }
    }//GEN-LAST:event_firefoxButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MainFrame f1 = new MainFrame();
        f1.show();
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void alLLEditButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alLLEditButton1ActionPerformed
        // TODO add your handling code here:
        DeletePropertyPanel panel = new DeletePropertyPanel(layeredPane);
        
        layeredPane.add(panel, new java.awt.GridBagConstraints());
        panel.setSize(layeredPane.getWidth(), layeredPane.getHeight());
        layeredPane.setLayer(panel, 1);
        mainPanel.setVisible(false);
        layeredPane.revalidate();
        layeredPane.repaint();
    }//GEN-LAST:event_alLLEditButton1ActionPerformed

    private void alLLEditButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alLLEditButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alLLEditButton2ActionPerformed

    private void alLLEditButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alLLEditButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alLLEditButton3ActionPerformed

    private void ConvertToCoorperateCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConvertToCoorperateCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConvertToCoorperateCheckBoxActionPerformed

    private void EditPropertyCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditPropertyCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditPropertyCheckBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminFrame().setVisible(true);
            }
        });
    }
    
    private ArrayList<JCheckBox> checks = new ArrayList<JCheckBox>();
    private JLabel[][] labels = new JLabel[11][3];
    private boolean chrome = true, edge = false, firefox = false;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private final javax.swing.JLabel ApproveProperty = new javax.swing.JLabel();
    private final javax.swing.JLabel ApproveProperty1 = new javax.swing.JLabel();
    private final javax.swing.JLabel ApproveProperty2 = new javax.swing.JLabel();
    private javax.swing.JCheckBox ApprovePropertyCheckBox;
    private final javax.swing.JLabel ConvertToCoorperate = new javax.swing.JLabel();
    private final javax.swing.JLabel ConvertToCoorperate1 = new javax.swing.JLabel();
    private final javax.swing.JLabel ConvertToCoorperate2 = new javax.swing.JLabel();
    private javax.swing.JCheckBox ConvertToCoorperateCheckBox;
    private final javax.swing.JLabel DeleteOffer = new javax.swing.JLabel();
    private final javax.swing.JLabel DeleteOffer1 = new javax.swing.JLabel();
    private final javax.swing.JLabel DeleteOffer2 = new javax.swing.JLabel();
    private javax.swing.JCheckBox DeleteOfferCheckBox;
    private final javax.swing.JLabel DeleteProperty = new javax.swing.JLabel();
    private final javax.swing.JLabel DeleteProperty1 = new javax.swing.JLabel();
    private final javax.swing.JLabel DeleteProperty2 = new javax.swing.JLabel();
    private javax.swing.JCheckBox DeletePropertyCheckBox;
    private final javax.swing.JLabel DeleteRequest = new javax.swing.JLabel();
    private final javax.swing.JLabel DeleteRequest1 = new javax.swing.JLabel();
    private final javax.swing.JLabel DeleteRequest2 = new javax.swing.JLabel();
    private javax.swing.JCheckBox DeleteRequestCheckBox;
    private final javax.swing.JLabel DeleteUser = new javax.swing.JLabel();
    private final javax.swing.JLabel DeleteUser1 = new javax.swing.JLabel();
    private final javax.swing.JLabel DeleteUser2 = new javax.swing.JLabel();
    private javax.swing.JCheckBox DeleteUserCheckBox;
    private final javax.swing.JLabel EditProperty = new javax.swing.JLabel();
    private final javax.swing.JLabel EditProperty1 = new javax.swing.JLabel();
    private final javax.swing.JLabel EditProperty2 = new javax.swing.JLabel();
    private javax.swing.JCheckBox EditPropertyCheckBox;
    private javax.swing.JCheckBox EditUserCheckBox;
    private final javax.swing.JLabel EditUserLabel = new javax.swing.JLabel();
    private final javax.swing.JLabel EditUserLabel1 = new javax.swing.JLabel();
    private final javax.swing.JLabel EditUserLabel2 = new javax.swing.JLabel();
    private javax.swing.JButton alLLEditButton;
    private javax.swing.JButton alLLEditButton1;
    private javax.swing.JButton alLLEditButton2;
    private javax.swing.JButton alLLEditButton3;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton chromeButton;
    private javax.swing.JButton deselectAllButton;
    private javax.swing.JButton edgeButton;
    private javax.swing.JButton firefoxButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLayeredPane layeredPane;
    private javax.swing.JButton loginEditButton;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton prTTEditButton;
    private javax.swing.JButton searchEditButton;
    private javax.swing.JButton selectAllButton;
    private javax.swing.JButton signupEditButton;
    private javax.swing.JButton testButton;
    // End of variables declaration//GEN-END:variables
}
