/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import demo.Methods;
import demo.PostRequesttest;
import demo.SearchTest;
import demo.SignupTest;
import demo.logintest;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.*;
import javax.swing.table.TableCellRenderer;
import org.junit.internal.TextListener;
import org.junit.runner.JUnitCore;
import ui.*;

/**
 *
 * @author Omar Fekry
 */
public class MainFrame extends javax.swing.JFrame {
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        layeredPane = new javax.swing.JLayeredPane();
        mainPanel = new javax.swing.JPanel();
        loginCheckBox = new javax.swing.JCheckBox();
        alLLCheckBox = new javax.swing.JCheckBox();
        coTTCheckBox = new javax.swing.JCheckBox();
        coLLCheckBox = new javax.swing.JCheckBox();
        rrLLCheckBox = new javax.swing.JCheckBox();
        prTTCheckBox = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        rrLLLabel = new javax.swing.JLabel();
        arLLEditButton = new javax.swing.JButton();
        loginEditButton = new javax.swing.JButton();
        coLLEditButton = new javax.swing.JButton();
        alLLLabel = new javax.swing.JLabel();
        rrTTCheckBox = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        coLLLabel = new javax.swing.JLabel();
        alLLEditButton = new javax.swing.JButton();
        searchCheckBox = new javax.swing.JCheckBox();
        signupEditButton = new javax.swing.JButton();
        signupCheckBox = new javax.swing.JCheckBox();
        arLLLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        loginLabel = new javax.swing.JLabel();
        rrLLEditButton = new javax.swing.JButton();
        arLLCheckBox = new javax.swing.JCheckBox();
        signupLabel = new javax.swing.JLabel();
        arTTCheckBox = new javax.swing.JCheckBox();
        prTTLabel = new javax.swing.JLabel();
        prTTEditButton = new javax.swing.JButton();
        buttonPanel = new javax.swing.JPanel();
        selectAllButton = new javax.swing.JButton();
        deselectAllButton = new javax.swing.JButton();
        testButton = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        arTTEditButton = new javax.swing.JButton();
        rrTTEditButton = new javax.swing.JButton();
        rrTTLabel = new javax.swing.JLabel();
        arTTLabel = new javax.swing.JLabel();
        searchLabel = new javax.swing.JLabel();
        coTTLabel = new javax.swing.JLabel();
        searchEditButton = new javax.swing.JButton();
        coTTEditButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rentup Automated Tester");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(715, 735));
        setMinimumSize(new java.awt.Dimension(715, 735));
        setName("mainFrame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(715, 735));
        setSize(new java.awt.Dimension(700, 700));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        layeredPane.setBackground(new java.awt.Color(255, 0, 102));
        layeredPane.setMaximumSize(new java.awt.Dimension(1400, 700));
        layeredPane.setMinimumSize(new java.awt.Dimension(1400, 700));
        layeredPane.setPreferredSize(new Dimension(1400, 700));
        layeredPane.setLayout(new java.awt.GridBagLayout());

        mainPanel.setBackground(new java.awt.Color(249, 249, 249));
        mainPanel.setMaximumSize(new java.awt.Dimension(1400, 700));
        mainPanel.setMinimumSize(new java.awt.Dimension(1400, 700));
        mainPanel.setName("mainPanel"); // NOI18N
        mainPanel.setPreferredSize(new java.awt.Dimension(1400, 700));
        mainPanel.setLayout(new java.awt.GridBagLayout());

        loginCheckBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        loginCheckBox.setSelected(true);
        loginCheckBox.setText("Login");
        loginCheckBox.setName("loginCheckBox"); // NOI18N
        loginCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginCheckBoxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 45;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(6, 25, 6, 0);
        mainPanel.add(loginCheckBox, gridBagConstraints);

        alLLCheckBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        alLLCheckBox.setSelected(true);
        alLLCheckBox.setText("Add Listing");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 45;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(6, 25, 6, 0);
        mainPanel.add(alLLCheckBox, gridBagConstraints);

        coTTCheckBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        coTTCheckBox.setSelected(true);
        coTTCheckBox.setText("Counter Offer");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.ipadx = 45;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 25, 6, 0);
        mainPanel.add(coTTCheckBox, gridBagConstraints);

        coLLCheckBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        coLLCheckBox.setSelected(true);
        coLLCheckBox.setText("Counter Offer");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.ipadx = 45;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(6, 25, 6, 0);
        mainPanel.add(coLLCheckBox, gridBagConstraints);

        rrLLCheckBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rrLLCheckBox.setSelected(true);
        rrLLCheckBox.setText("Reject Request");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.ipadx = 45;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(6, 25, 6, 0);
        mainPanel.add(rrLLCheckBox, gridBagConstraints);

        prTTCheckBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        prTTCheckBox.setSelected(true);
        prTTCheckBox.setText("Post A Request");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 45;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(6, 25, 6, 0);
        mainPanel.add(prTTCheckBox, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setText("Tenant:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(16, 15, 16, 0);
        mainPanel.add(jLabel8, gridBagConstraints);

        rrLLLabel.setMaximumSize(new java.awt.Dimension(35, 35));
        rrLLLabel.setMinimumSize(new java.awt.Dimension(35, 35));
        rrLLLabel.setPreferredSize(new java.awt.Dimension(35, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.ipadx = 28;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.1;
        mainPanel.add(rrLLLabel, gridBagConstraints);

        arLLEditButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        arLLEditButton.setText("Edit Values");
        arLLEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arLLEditButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.insets = new java.awt.Insets(0, 16, 0, 16);
        mainPanel.add(arLLEditButton, gridBagConstraints);

        loginEditButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        loginEditButton.setText("Edit Values");
        loginEditButton.setName("loginEditButton"); // NOI18N
        loginEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginEditButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 16, 0, 16);
        mainPanel.add(loginEditButton, gridBagConstraints);

        coLLEditButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        coLLEditButton.setText("Edit Values");
        coLLEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coLLEditButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.insets = new java.awt.Insets(0, 16, 0, 16);
        mainPanel.add(coLLEditButton, gridBagConstraints);

        alLLLabel.setMaximumSize(new java.awt.Dimension(35, 35));
        alLLLabel.setMinimumSize(new java.awt.Dimension(35, 35));
        alLLLabel.setPreferredSize(new java.awt.Dimension(35, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 28;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.1;
        mainPanel.add(alLLLabel, gridBagConstraints);

        rrTTCheckBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rrTTCheckBox.setSelected(true);
        rrTTCheckBox.setText("Reject Request");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.ipadx = 45;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 25, 6, 0);
        mainPanel.add(rrTTCheckBox, gridBagConstraints);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setText("General:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(16, 15, 16, 0);
        mainPanel.add(jLabel10, gridBagConstraints);

        coLLLabel.setMaximumSize(new java.awt.Dimension(35, 35));
        coLLLabel.setMinimumSize(new java.awt.Dimension(35, 35));
        coLLLabel.setPreferredSize(new java.awt.Dimension(35, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.ipadx = 28;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.1;
        mainPanel.add(coLLLabel, gridBagConstraints);

        alLLEditButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        alLLEditButton.setText("Edit Values");
        alLLEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alLLEditButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(0, 16, 0, 16);
        mainPanel.add(alLLEditButton, gridBagConstraints);

        searchCheckBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        searchCheckBox.setSelected(true);
        searchCheckBox.setText("Search");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 45;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(6, 25, 6, 0);
        mainPanel.add(searchCheckBox, gridBagConstraints);

        signupEditButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        signupEditButton.setText("Edit Values");
        signupEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupEditButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 16, 0, 16);
        mainPanel.add(signupEditButton, gridBagConstraints);

        signupCheckBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        signupCheckBox.setSelected(true);
        signupCheckBox.setText("Signup");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 45;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(6, 25, 6, 0);
        mainPanel.add(signupCheckBox, gridBagConstraints);

        arLLLabel.setMaximumSize(new java.awt.Dimension(35, 35));
        arLLLabel.setMinimumSize(new java.awt.Dimension(35, 35));
        arLLLabel.setPreferredSize(new java.awt.Dimension(35, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.ipadx = 28;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.1;
        mainPanel.add(arLLLabel, gridBagConstraints);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setText("Landlord:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(16, 15, 16, 0);
        mainPanel.add(jLabel9, gridBagConstraints);

        loginLabel.setMaximumSize(new java.awt.Dimension(35, 35));
        loginLabel.setMinimumSize(new java.awt.Dimension(35, 35));
        loginLabel.setName("loginStatusLabel"); // NOI18N
        loginLabel.setPreferredSize(new java.awt.Dimension(35, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 28;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.1;
        mainPanel.add(loginLabel, gridBagConstraints);

        rrLLEditButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rrLLEditButton.setText("Edit Values");
        rrLLEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rrLLEditButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.insets = new java.awt.Insets(0, 16, 0, 16);
        mainPanel.add(rrLLEditButton, gridBagConstraints);

        arLLCheckBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        arLLCheckBox.setSelected(true);
        arLLCheckBox.setText("Accept Request");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.ipadx = 45;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(6, 25, 6, 0);
        mainPanel.add(arLLCheckBox, gridBagConstraints);

        signupLabel.setMaximumSize(new java.awt.Dimension(35, 35));
        signupLabel.setMinimumSize(new java.awt.Dimension(35, 35));
        signupLabel.setPreferredSize(new java.awt.Dimension(35, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 28;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.1;
        mainPanel.add(signupLabel, gridBagConstraints);

        arTTCheckBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        arTTCheckBox.setSelected(true);
        arTTCheckBox.setText("Accept Request");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 45;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 25, 6, 0);
        mainPanel.add(arTTCheckBox, gridBagConstraints);

        prTTLabel.setMaximumSize(new java.awt.Dimension(35, 35));
        prTTLabel.setMinimumSize(new java.awt.Dimension(35, 35));
        prTTLabel.setName(""); // NOI18N
        prTTLabel.setPreferredSize(new java.awt.Dimension(35, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 28;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.1;
        mainPanel.add(prTTLabel, gridBagConstraints);

        prTTEditButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        prTTEditButton.setText("Edit Values");
        prTTEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prTTEditButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(0, 16, 0, 16);
        mainPanel.add(prTTEditButton, gridBagConstraints);

        buttonPanel.setBackground(mainPanel.getBackground());
        buttonPanel.setMaximumSize(new java.awt.Dimension(362, 35));
        buttonPanel.setMinimumSize(new java.awt.Dimension(362, 35));
        buttonPanel.setName("buttonPanel"); // NOI18N
        buttonPanel.setPreferredSize(new java.awt.Dimension(362, 35));
        buttonPanel.setLayout(new java.awt.GridBagLayout());

        selectAllButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        selectAllButton.setText("Select All");
        selectAllButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        selectAllButton.setName("loginEditButton"); // NOI18N
        selectAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectAllButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        buttonPanel.add(selectAllButton, gridBagConstraints);

        deselectAllButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        deselectAllButton.setText("Deselect All");
        deselectAllButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        deselectAllButton.setName("loginEditButton"); // NOI18N
        deselectAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deselectAllButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        buttonPanel.add(deselectAllButton, gridBagConstraints);

        testButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        testButton.setText("Start Testing");
        testButton.setMaximumSize(new java.awt.Dimension(140, 31));
        testButton.setMinimumSize(new java.awt.Dimension(140, 31));
        testButton.setName("loginEditButton"); // NOI18N
        testButton.setPreferredSize(new java.awt.Dimension(140, 31));
        testButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 0.1;
        buttonPanel.add(testButton, gridBagConstraints);

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chrome", "Edge", "Firefox" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        buttonPanel.add(jComboBox1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 13, 0, 13);
        mainPanel.add(buttonPanel, gridBagConstraints);

        arTTEditButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        arTTEditButton.setText("Edit Values");
        arTTEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arTTEditButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.insets = new java.awt.Insets(0, 16, 0, 16);
        mainPanel.add(arTTEditButton, gridBagConstraints);

        rrTTEditButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rrTTEditButton.setText("Edit Values");
        rrTTEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rrTTEditButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.insets = new java.awt.Insets(0, 16, 0, 16);
        mainPanel.add(rrTTEditButton, gridBagConstraints);

        rrTTLabel.setMaximumSize(new java.awt.Dimension(35, 35));
        rrTTLabel.setMinimumSize(new java.awt.Dimension(35, 35));
        rrTTLabel.setPreferredSize(new java.awt.Dimension(35, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.ipadx = 28;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        mainPanel.add(rrTTLabel, gridBagConstraints);

        arTTLabel.setMaximumSize(new java.awt.Dimension(35, 35));
        arTTLabel.setMinimumSize(new java.awt.Dimension(35, 35));
        arTTLabel.setPreferredSize(new java.awt.Dimension(35, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 28;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        mainPanel.add(arTTLabel, gridBagConstraints);

        searchLabel.setMaximumSize(new java.awt.Dimension(35, 35));
        searchLabel.setMinimumSize(new java.awt.Dimension(35, 35));
        searchLabel.setPreferredSize(new java.awt.Dimension(35, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 28;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        mainPanel.add(searchLabel, gridBagConstraints);

        coTTLabel.setMaximumSize(new java.awt.Dimension(35, 35));
        coTTLabel.setMinimumSize(new java.awt.Dimension(35, 35));
        coTTLabel.setPreferredSize(new java.awt.Dimension(35, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.ipadx = 28;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        mainPanel.add(coTTLabel, gridBagConstraints);

        searchEditButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        searchEditButton.setText("Edit Values");
        searchEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchEditButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 16, 0, 16);
        mainPanel.add(searchEditButton, gridBagConstraints);

        coTTEditButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        coTTEditButton.setText("Edit Values");
        coTTEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coTTEditButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.insets = new java.awt.Insets(0, 16, 0, 16);
        mainPanel.add(coTTEditButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.ipady = 4;
        layeredPane.add(mainPanel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 6);
        getContentPane().add(layeredPane, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectAllButtonActionPerformed
        for(JCheckBox cb : checks)
            cb.setSelected(true);
    }//GEN-LAST:event_selectAllButtonActionPerformed

    private void arLLEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arLLEditButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arLLEditButtonActionPerformed

    private void rrLLEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rrLLEditButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rrLLEditButtonActionPerformed

    private void alLLEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alLLEditButtonActionPerformed
        AddListingPanel panel = new AddListingPanel(layeredPane);
        
        layeredPane.add(panel, new java.awt.GridBagConstraints());
        panel.setSize(layeredPane.getWidth(), layeredPane.getHeight());
        layeredPane.setLayer(panel, 1);
        mainPanel.setVisible(false);
        layeredPane.revalidate();
        layeredPane.repaint();
    }//GEN-LAST:event_alLLEditButtonActionPerformed

    private void prTTEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prTTEditButtonActionPerformed
        // TODO add your handling code here:
        PostRequestPanel panel = new PostRequestPanel(layeredPane);
        
        layeredPane.add(panel, new java.awt.GridBagConstraints());
        panel.setSize(layeredPane.getWidth(), layeredPane.getHeight());
        layeredPane.setLayer(panel, 1);
        mainPanel.setVisible(false);
        layeredPane.revalidate();
        layeredPane.repaint();
    }//GEN-LAST:event_prTTEditButtonActionPerformed

    private void signupEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupEditButtonActionPerformed
        SignupPanel panel = new SignupPanel(layeredPane);
        
        layeredPane.add(panel, new java.awt.GridBagConstraints());
        panel.setSize(layeredPane.getWidth(), layeredPane.getHeight());
        layeredPane.setLayer(panel, 1);
        mainPanel.setVisible(false);
        layeredPane.revalidate();
        layeredPane.repaint();
    }//GEN-LAST:event_signupEditButtonActionPerformed

    private void coLLEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coLLEditButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coLLEditButtonActionPerformed

    private void deselectAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deselectAllButtonActionPerformed
        for(JCheckBox cb : checks)
            cb.setSelected(false);
    }//GEN-LAST:event_deselectAllButtonActionPerformed

    private void testButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testButtonActionPerformed
        
        
        for(JLabel label : labels)
            label.setIcon(null);
        
        if (loginCheckBox.isSelected()){
            loginLabel.setIcon(new ImageIcon(getClass().getResource("/Resources/loading.gif")));
            JUnitCore junit = new JUnitCore();
            junit.addListener(new TextListener(System.out));
            new Thread(){
                public void run(){
                    if (junit.run(logintest.class).wasSuccessful())
                        loginLabel.setIcon(new ImageIcon(getClass().getResource("/Resources/check.png")));
                    else
                        loginLabel.setIcon(new ImageIcon(getClass().getResource("/Resources/cross.png")));
                }
            }.start();
           
        }
        try {
            Thread.sleep(3000);
        } catch (InterruptedException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        Methods.browser = "Edge";
        Methods.domain = "https://rentup.co/";
        
        if (signupCheckBox.isSelected()){
            signupLabel.setIcon(new ImageIcon(getClass().getResource("/Resources/loading.gif")));
            JUnitCore junit = new JUnitCore();
            junit.addListener(new TextListener(System.out));
            new Thread(){
                public void run(){
                    if (junit.run(SignupTest.class).wasSuccessful())
                        signupLabel.setIcon(new ImageIcon(getClass().getResource("/Resources/check.png")));
                    else
                        signupLabel.setIcon(new ImageIcon(getClass().getResource("/Resources/cross.png")));
                }
            }.start(); 
           
        }
        
        try {
            Thread.sleep(3000);
        } catch (InterruptedException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Methods.browser = "Firefox";
        Methods.domain = "https://rentup.com.eg/";
        
        if (searchCheckBox.isSelected()){
            searchLabel.setIcon(new ImageIcon(getClass().getResource("/Resources/loading.gif")));
            JUnitCore junit = new JUnitCore();
            junit.addListener(new TextListener(System.out));
            new Thread(){
                public void run(){
                    if (junit.run(SearchTest.class).wasSuccessful())
                        searchLabel.setIcon(new ImageIcon(getClass().getResource("/Resources/check.png")));
                    else
                        searchLabel.setIcon(new ImageIcon(getClass().getResource("/Resources/cross.png")));
                }
            }.start();
        }
        
        if (prTTCheckBox.isSelected()){
            prTTLabel.setIcon(new ImageIcon(getClass().getResource("/Resources/loading.gif")));
            JUnitCore junit = new JUnitCore();
            junit.addListener(new TextListener(System.out));
            new Thread(){
                public void run(){
                    if (junit.run(PostRequesttest.class).wasSuccessful())
                        prTTLabel.setIcon(new ImageIcon(getClass().getResource("/Resources/check.png")));
                    else
                        prTTLabel.setIcon(new ImageIcon(getClass().getResource("/Resources/cross.png")));
                }
            }.start();
        }
        
    }//GEN-LAST:event_testButtonActionPerformed

    private void loginEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginEditButtonActionPerformed
        LoginPanel panel = new LoginPanel(layeredPane);
        
        layeredPane.add(panel, new java.awt.GridBagConstraints());
        panel.setSize(layeredPane.getWidth(), layeredPane.getHeight());
        layeredPane.setLayer(panel, 1);
        mainPanel.setVisible(false);
        layeredPane.revalidate();
        layeredPane.repaint();
    }//GEN-LAST:event_loginEditButtonActionPerformed

    private void arTTEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arTTEditButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arTTEditButtonActionPerformed

    private void rrTTEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rrTTEditButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rrTTEditButtonActionPerformed

    private void coTTEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coTTEditButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coTTEditButtonActionPerformed

    private void loginCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginCheckBoxActionPerformed

    private void searchEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchEditButtonActionPerformed
        
        searchPanel panel = new searchPanel(layeredPane);
        
        layeredPane.add(panel, new java.awt.GridBagConstraints());
        panel.setSize(layeredPane.getWidth(), layeredPane.getHeight());
        layeredPane.setLayer(panel, 1);
        mainPanel.setVisible(false);
        layeredPane.revalidate();
        layeredPane.repaint();
        
        
        
        
    }//GEN-LAST:event_searchEditButtonActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        checks.add(loginCheckBox);
        checks.add(signupCheckBox);
        checks.add(searchCheckBox);
        checks.add(prTTCheckBox);
        checks.add(arTTCheckBox);
        checks.add(rrTTCheckBox);
        checks.add(coTTCheckBox);
        checks.add(alLLCheckBox);
        checks.add(arLLCheckBox);
        checks.add(rrLLCheckBox);
        checks.add(coLLCheckBox);
        
        labels.add(loginLabel);
        labels.add(signupLabel);
        labels.add(searchLabel);
        labels.add(prTTLabel);
        labels.add(arTTLabel);
        labels.add(rrTTLabel);
        labels.add(coTTLabel);
        labels.add(alLLLabel);
        labels.add(arLLLabel);
        labels.add(rrLLLabel);
        labels.add(coLLLabel);
    }//GEN-LAST:event_formWindowOpened

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        
        String choice = jComboBox1.getSelectedItem().toString();
        Methods.setCellData(choice, 1, 2);
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    
    private ArrayList<JCheckBox> checks = new ArrayList<JCheckBox>();
    private ArrayList<JLabel> labels = new ArrayList<JLabel>();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox alLLCheckBox;
    private javax.swing.JButton alLLEditButton;
    private javax.swing.JLabel alLLLabel;
    private javax.swing.JCheckBox arLLCheckBox;
    private javax.swing.JButton arLLEditButton;
    private javax.swing.JLabel arLLLabel;
    private javax.swing.JCheckBox arTTCheckBox;
    private javax.swing.JButton arTTEditButton;
    private javax.swing.JLabel arTTLabel;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JCheckBox coLLCheckBox;
    private javax.swing.JButton coLLEditButton;
    private javax.swing.JLabel coLLLabel;
    private javax.swing.JCheckBox coTTCheckBox;
    private javax.swing.JButton coTTEditButton;
    private javax.swing.JLabel coTTLabel;
    private javax.swing.JButton deselectAllButton;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane layeredPane;
    private javax.swing.JCheckBox loginCheckBox;
    private javax.swing.JButton loginEditButton;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JCheckBox prTTCheckBox;
    private javax.swing.JButton prTTEditButton;
    private javax.swing.JLabel prTTLabel;
    private javax.swing.JCheckBox rrLLCheckBox;
    private javax.swing.JButton rrLLEditButton;
    private javax.swing.JLabel rrLLLabel;
    private javax.swing.JCheckBox rrTTCheckBox;
    private javax.swing.JButton rrTTEditButton;
    private javax.swing.JLabel rrTTLabel;
    private javax.swing.JCheckBox searchCheckBox;
    private javax.swing.JButton searchEditButton;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JButton selectAllButton;
    private javax.swing.JCheckBox signupCheckBox;
    private javax.swing.JButton signupEditButton;
    private javax.swing.JLabel signupLabel;
    private javax.swing.JButton testButton;
    // End of variables declaration//GEN-END:variables
}
